version: "3"
services:
  pg1:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
  pg2:
    image: "postgres:10"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: test
  bucardo:
    build: .
    restart: unless-stopped
    command: ""
    depends_on:
      - pg1
      - pg2
